config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "main#index"

  get "/about", to: "about#index"

  get "/password", to: "passwords#edit"
  patch "/password", to: "passwords#update"

  get "/sign_up", to: "registerations#new"
  post "/sign_up", to: "registerations#create"

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, email: true,  :length => { maximum: 256 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
      
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def required_logged_in!
        redirect_to sign_in_path, alert: "You must be sign in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :required_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated successfully!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registerations_controller.rb
class RegisterationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Account Created successfully!"
        else
            render :new, status: :unprocessable_entity
        end          
    end

    private
    
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged In Successfully!"
        else
            flash[:alert] = "Invalid email or password"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You're Logged out!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/main/index.html.erb
<div>
    <h1 class="text-center">Welcome from ScheduledTweets</h1>
</div>

app/views/registerations/new.html.erb
<h1 class="mb-3">Sign Up Form</h1>

<%= form_with model: @user, url: sign_up_path do |form| %>
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.text_field :email, class: "form-control w-50", placeholder: "example@gmail.com" %>
    </div>

    <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control w-50", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control w-50", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Sign Up", class: "btn btn-primary px-4" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center bg-primary text-white p-2 mt-auto">
    Copyright &copy; 2024
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-fluid">
    <%= link_to "ScheduledTweets", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
        </li>
    </div>
    <div>
        <% if Current.user %>
            <span class="mx-2"><%= link_to Current.user.email, password_path %></span>
        <% end %>
    </div>
    <div>
        <% if session[:user_id] %>
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-sm btn-outline-danger" %>
        <% else %>
            <%= link_to "Sign Up", sign_up_path, class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to "Sign In", sign_in_path, class: "btn btn-sm btn-outline-success" %>
        <% end %>
    </div>
  </div>
</nav>